# This workflow compiles a LaTeX resume using TeXLive 2020 and deploys the PDF to GitHub Pages.
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Permissions needed for deploying to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Environment setup for GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Compile the LaTeX document using TeXLive 2020
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: resume.tex
          texlive_version: 2020
      
      # Prepare the PDF for deployment (move to a directory for upload)
      - name: Prepare PDF artifact
        run: |
          mkdir output
          mv resume.pdf output/gasekjames.pdf
      
      # Upload the directory contents as a Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
